---
title: "WDAFS Talk Leaflet"
author: "Madeline Jovanovich"
date: "5/21/2018"
output: 
  html_document: 
    highlight: tango
    theme: paper
---

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(leaflet)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(scales)
library(knitr)
library(ggthemes)
library(RColorBrewer)
library(colorspace)
library(scales)
library(viridis)
library(DT)
```

```{r Reading in data, echo=FALSE}
#Need to change to KNB url once it is generated
escapement_goals <- read.csv("~/R/Esc_goals_evaluated.csv", stringsAsFactors = FALSE)
```

```{r, include=FALSE}
mean_esc <- escapement_goals %>%
  group_by(SASAP.Region, LocationID, Lat, Lon, Species) %>%
  summarize (meanby_loc = mean(annualCount)) %>%
   mutate_if(is.numeric, funs(round(., 0)))
datatable(mean_esc)
```


```{r, fig.align='center', echo=FALSE}
locations <- escapement_goals %>% 
  distinct(SASAP.Region, LocationID, Lat, Lon) %>% 
  drop_na()
```
```{r, echo=FALSE}
datatable(locations)
```

```{r, echo=FALSE}
markerIcon <- makeIcon(
  iconUrl = "~/R/icons/salmon.png",
  iconWidth = 25, iconHeight = 41,
  iconAnchorX = 12, iconAnchorY = 41
)
```
```{r, fig.align='center', echo=FALSE}

leaflet(mean_esc) %>% 
  addTiles() %>% 
  addMarkers(~ Lon, ~ Lat, popup = ~ Species, icon = markerIcon, clusterOptions = markerClusterOptions())

```